DDD-Community/DDD-12-MOYORAK-API

- .github/workflows/deploy.yml
- 배포 스크립트를 public EC2 내로 옮겼습니다.
---
- 배포 명령 제거
> build: #34 EC2 내의 sh 실행하는 방식으로 변경

- src/main/java/com/moyorak/api/auth/domain/User.java
- src/main/java/com/moyorak/api/auth/dto/SignUpResponse.java
- src/main/java/com/moyorak/config/security/CustomOAuth2SuccessHandler.java
- src/main/java/com/moyorak/config/security/CustomOAuth2UserService.java
`CustomOAuth2UserService`에서 프로필 사진 정보를 가져오고, 
이미 회원의 경우 `isNew` 값을 false로
신규 회원일 때에는 `isNew` 값을 true로 return합니다.
`CustomOAuth2SuccessHandler`에서 `isNew` 값을 통해 분기 처리 합니다.
---
- 프로필 사진 저장하도록 추가
- isNew 구분 값 추가
> feat: #53 최초 회원 가입의 경우 기본 정보를 반환한다

- src/main/java/com/moyorak/api/auth/controller/TokenController.java
- src/main/java/com/moyorak/api/auth/domain/User.java
- src/main/java/com/moyorak/api/auth/domain/UserToken.java
- src/main/java/com/moyorak/api/auth/dto/SignInRequest.java
- src/main/java/com/moyorak/api/auth/dto/SignUpResponse.java
- src/main/java/com/moyorak/api/auth/repository/TokenRepository.java
- src/main/java/com/moyorak/api/auth/service/TokenService.java
- src/main/java/com/moyorak/config/security/CustomOAuth2SuccessHandler.java
- src/main/java/com/moyorak/config/security/CustomOAuth2UserService.java
- src/main/java/com/moyorak/config/security/JwtTokenProvider.java
- src/test/java/com/moyorak/api/auth/domain/UserFixture.java
- src/test/java/com/moyorak/api/auth/service/TokenServiceTest.java
⚠️ #54 가 선행 되어야 합니다.
토큰 발급을 별도 Service에서 처리할 수 있도록 `TokenService`를 생성하였습니다.
refresh 토큰은 이후 추가 예정입니다.
---
- Token Entity 생성
- 회원 id 검증 후 유효한 경우에만 토큰 발급 받을 수 있도록 기능 추가
- `CustomOAuth2SuccessHandler`에서 토큰 발급 받던 것을 `TokenService`로 분리
- 테스트 로그인 용 API 추가
> feat: #50 토큰 저장 기능 추가

- src/main/java/com/moyorak/config/security/JwtAuthenticationFilter.java
- src/test/java/com/moyorak/config/security/JwtAuthenticationFilterTest.java
- 로그인의 경우 JWT 토큰이 없어 필터에서 처리 되지 않도록 예외 조건을 추가 하였습니다.
---
- `JwtAuthenticationFilter`에 `shouldNotFilter` 구현
- 테스트 코드 케이스 추가
> chore: #58 로그인 요청 시 JWT 필터에서 제외 되도록 조건 추가

- src/main/java/com/moyorak/config/security/SecurityConfig.java
- 토큰 발급을 위한 endpoint의 경우 토큰이 불필요한데, 시큐리티 필터에 걸리는 문제로 제거 되기 위해 조건을 추가하였습니다.
---
- `SecurityConfig` endpoint 추가
> fix: #113 토큰 발급 endpoint 시큐리티 필터에서 처리되지 않도록 조건 추가

- src/main/java/com/moyorak/api/restaurant/controller/RestaurantController.java
- src/main/java/com/moyorak/api/restaurant/dto/RestaurantResponse.java
- src/main/java/com/moyorak/api/restaurant/dto/RestaurantSearchRequest.java
- src/main/java/com/moyorak/infra/client/kakao/KakaoClient.java
- src/main/java/com/moyorak/infra/client/kakao/KakaoClientConfig.java
- src/main/java/com/moyorak/infra/client/kakao/KakaoSearcher.java
- src/main/java/com/moyorak/infra/client/kakao/dto/KakaoPlace.java
- src/main/java/com/moyorak/infra/client/kakao/dto/KakaoSearchResponse.java
- src/main/java/com/moyorak/infra/client/kakao/dto/KakoSearchResponse.java
- src/test/java/com/moyorak/infra/client/kakao/KakaoSearcherTest.java
- src/test/java/com/moyorak/infra/client/kakao/dto/KakaoSearchResponseTest.java
- 위도, 경도 변수명 변경
- 잘못된 클래스 이름 변경
- 테스트 코드 추가
---
- 기존에 얘기했던 카카오와 관련된 부분에서만 x,y로 놓고 나머지 저희 쪽 로직에서는 **longitude**, **latitude**로 변경하였습니다.
- **kako**로 잘못 표기된 이름을 수정하였습니다.
- 카카오 api로 조회하는 과정에서 응답 받는 데이터를 변경하였습니다.
- 카카오가 실제로 제공해주는 총 데이터를 넘을 경우 `KakaoSearcher` 가 빈 리스트를 반환하는 테스트 로직을 추가하였습니다.
> feat: #90 카카오 api 조회 수정

- src/main/java/com/moyorak/api/auth/controller/UserDailyStateController.java
- src/main/java/com/moyorak/api/auth/domain/State.java
- src/main/java/com/moyorak/api/auth/domain/UserDailyState.java
- src/main/java/com/moyorak/api/auth/dto/UserDailyStateRequest.java
- src/main/java/com/moyorak/api/auth/dto/UserDailyStateResponse.java
- src/main/java/com/moyorak/api/auth/repository/UserDailyStateRepository.java
- src/main/java/com/moyorak/api/auth/service/UserDailyStateService.java
- src/test/java/com/moyorak/api/auth/domain/UserDailyStateFixture.java
- src/test/java/com/moyorak/api/auth/service/UserDailyStateServiceTest.java
혼바 상태를 조회, 수정/저장 하는 기능을 추가 하였습니다.
1. 혼밥 상태를 조회 시, 서버에서 오늘 날짜의 혼밥 상태가 있는지 조회를 합니다.
2. 조회 시, 저장된 혼밥 상태가 없다면, 'OFF' 값을 내려 보냅니다.
3. 혼밥 상태를 수정 할 때, 토큰 값과 유저 ID 를 비교하여 정상적인 유저 정보인지를 확인합니다.
4. 혼밥 상태를 수정 할 때, 혼밥 상태가 존재하면, 수정을 합니다.
5. 혼밥 상태를 수정 할 때, 혼밥 상태가 존재하지 않으면, 해당 상태 값으로 혼밥 상태를 저장합니다.
---
- 충돌을 방지하여 `UserDailyState` 이름으로 컨트롤러, 서비스를 생성하였습니다.
> feat: #92 혼밥 상태 조회, 수정/저장 api 개발

- .github/workflows/deploy.yml
- .github/workflows/gradle.yml
- build.gradle.kts
- src/main/java/com/moyorak/api/image/controller/ImageController.java
- src/main/java/com/moyorak/api/image/dto/ImageSaveRequest.java
- src/main/java/com/moyorak/api/image/dto/ImageSaveResponse.java
- src/main/java/com/moyorak/api/image/service/ImageService.java
- src/main/java/com/moyorak/config/exception/BusinessException.java
- src/main/java/com/moyorak/infra/aws/s3/S3Adapter.java
- src/main/java/com/moyorak/infra/aws/s3/S3Config.java
- src/main/java/com/moyorak/infra/aws/s3/S3Properties.java
- src/main/resources/application-local-tepmlate.yml
- src/main/resources/application.yml
- src/test/java/com/moyorak/api/image/dto/ImageSaveRequestTest.java
- src/test/java/com/moyorak/infra/aws/s3/S3AdapterTest.java
업로드 하고자하는 파일의 확장명을 입력하면 사전 인증이 완료 되어 업로드 가능한 URL을 발급 받습니다.
내부적으로 저장을 위한 path 값과 함께 응답을 내려줄 수 있는 기능을 추가하였습니다.
해당 기능이 머지되면 `application-local.yml`을 추가해주세요.
노션에 해당 항목 추가 해 두었습니다.
유효한 확장명은 `jpg` `png` `jpeg` 입니다.
---
- S3 SDK dependency 추가
- S3Properties 추가
- S3 버킷에 이미지 업로드를 위한 PresignedURL 발급 기능 추가
> feat: #100 PresignedUrl 업로드 url 발급 받는 기능 추가

- src/main/java/com/moyorak/api/team/controller/TeamController.java
- src/main/java/com/moyorak/api/team/domain/TeamSearch.java
- src/main/java/com/moyorak/api/team/dto/TeamSearchListResponse.java
- src/main/java/com/moyorak/api/team/dto/TeamSearchRequest.java
- src/main/java/com/moyorak/api/team/dto/TeamSearchResponse.java
- src/main/java/com/moyorak/api/team/repository/TeamRepository.java
- src/main/java/com/moyorak/api/team/service/TeamService.java
- src/test/java/com/moyorak/api/team/dto/TeamSearchRequestTest.java
-팀 ID 혹은 이름을 통해 팀 리스트를 조회합니다.
엔티티는 검색 전용 엔티티를 별도로 생성하였습니다.
팀 ID 혹은 이름이 없는 경우 유효성 검증이 실패하게 됩니다.
팀 정보는 최대 5개만 보이게 됩니다.
---
- 검색 전용 Team 엔티티 생성
- 팀 ID 혹은 이름을 받아 검색하도록 기능 추가
- 팀 ID 혹은 이름 모두 NULL이면 유효성 검증 실패하는 조건 추가
> feat: #128 팀 ID 혹은 이름을 통해 팀 정보 조회할 수 있는 API 추가

- src/main/java/com/moyorak/api/team/controller/TeamInvitationController.java
- src/main/java/com/moyorak/api/team/controller/TeamRestaurantController.java
- src/main/java/com/moyorak/api/team/domain/InvitationToken.java
- src/main/java/com/moyorak/api/team/domain/TeamInvitation.java
- src/main/java/com/moyorak/api/team/domain/TeamUserNotFoundException.java
- src/main/java/com/moyorak/api/team/dto/TeamInvitationCreateResponse.java
- src/main/java/com/moyorak/api/team/repository/TeamInvitationRepository.java
- src/main/java/com/moyorak/api/team/repository/TeamUserRepository.java
- src/main/java/com/moyorak/api/team/service/TeamInvitationService.java
- src/test/java/com/moyorak/api/team/service/TeamInvitationServiceTest.java
- 초대 링크 생성 기능 개발
---
- 초대 링크 생성 기능을 개발했습니다.
개발 중에 든 생각이 어차피 프론트 단에서 사용할 url을 백엔드에서 내려줘야하는데, 백엔드에서는 그냥 UUID를 내려주고
링크 생성을 프론트에서 책임지는 것도 괜찮겠다고 생각이 들었습니다. 요건 다음 회의때 한번 고려해보면 좋을 것  같습니다.
- 일단 토큰 유효시간을 하루로 설정하였습니다.
> feat: #141 초대 링크 생성

- src/main/java/com/moyorak/api/team/controller/TeamInvitationController.java
- src/main/java/com/moyorak/api/team/domain/TeamInvitation.java
- src/main/java/com/moyorak/api/team/domain/TeamInvitationTokenNotFoundException.java
- src/main/java/com/moyorak/api/team/dto/TeamInvitationDetailResponse.java
- src/main/java/com/moyorak/api/team/repository/TeamInvitationRepository.java
- src/main/java/com/moyorak/api/team/service/TeamInvitationService.java
- src/test/java/com/moyorak/api/team/domain/TeamInvitationFixture.java
- src/test/java/com/moyorak/api/team/domain/TeamInvitationTest.java
- src/test/java/com/moyorak/api/team/service/TeamInvitationServiceTest.java
- 팀 초대 api url에 안에 있는 토큰으로 검증 및 필요한 데이터 조회 기능 개발
- 테스트 코드 작성
---
- 화면 및 요구사항에 초대 링크로 초대시 가입까지 되는 흐름이 아니라 팀과 회사 정보만 내려주면 되기 때문에
필요한 데이터만 내려주도록 구현했습니다.
> fear: #143 초대 링크를 통해 팀 회사 정보 조회하기

- src/main/java/com/moyorak/api/history/domain/ViewHistory.java
- src/main/java/com/moyorak/api/history/service/HistoryEventHandler.java
- src/main/java/com/moyorak/api/team/controller/TeamRestaurantController.java
- src/main/java/com/moyorak/api/team/dto/TeamRestaurantViewEvent.java
- src/main/java/com/moyorak/api/team/service/TeamRestaurantEventPublisher.java
- src/main/java/com/moyorak/api/team/service/TeamRestaurantService.java
- src/test/java/com/moyorak/api/team/service/TeamRestaurantServiceTest.java
- 이벤트 처리 기반의 조회 저장 기능 개발
- 기능 추가로 인한 기존 팀 맛집 조회에 필요한 파라미터 추가
- 테스트 코드 수정
---
이벤트 처리 기반으로 팀 맛집 조회 시 조회 기록을 저장하는 기능을 개발했습니다.
> feat: #169 팀 맛집 상세 조회 시 본인 조회 기록에 저장

- src/main/java/com/moyorak/api/team/controller/TeamInvitationController.java
- src/main/java/com/moyorak/api/team/dto/TeamInvitationCreateResponse.java
- src/main/java/com/moyorak/api/team/service/TeamInvitationService.java
- src/test/java/com/moyorak/api/team/service/TeamInvitationServiceTest.java
- 초대 링크 생성에서 토큰 생성으로 변경
---
프론트 부분에서 링크를 생성해주고 백엔드 부분에서 토큰 생성만 담당하도록 변경해주었습니다.
(초대 링크 URL이 프론트 라우팅 URL로 생성되어야하기 때문)
> refactor: #170 초대 링크 생성에서 토큰 생성으로 변경

- src/main/java/com/moyorak/api/review/controller/ReviewController.java
- src/main/java/com/moyorak/api/review/domain/ReviewServingTime.java
- src/main/java/com/moyorak/api/review/domain/ReviewWaitingTime.java
- src/main/java/com/moyorak/api/review/dto/ReviewServingTimeResponse.java
- src/main/java/com/moyorak/api/review/dto/ReviewWaitingTimeResponse.java
- src/main/java/com/moyorak/api/review/repository/ReviewServingTimeRepository.java
- src/main/java/com/moyorak/api/review/repository/ReviewWaitingTimeRepository.java
- src/main/java/com/moyorak/api/review/service/ReviewService.java
- src/test/java/com/moyorak/api/review/domain/ReviewServingTimeFixture.java
- src/test/java/com/moyorak/api/review/domain/ReviewWaitingTimeFixture.java
- src/test/java/com/moyorak/api/review/service/ReviewServiceTest.java
- 리뷰 대기 시간 조회 기능 개발
- 리뷰 서빙 시간 조회 기능 개발
---
- 서빙 시간, 대기 시간 옵션을 내려주기 위한 API
-  `Review` 의 대기시간, 서빙 시간에 대한 값을 , `ReviewServingTime` `ReviewWaitingTime` 의 Integer 값(servingTimeValue, waitingTimeValue) 으로 넣으려고 합니다.  `TeamRestaurant` 의 평균값은 리뷰들의  Integer 값 을 평균내고, 해당 값 과 가장 가까운 값으로 조회 되는 `ReviewServingTime` `ReviewWaitingTime` 들의 `servingTime` `waitingTime` 값을 내려 주려 합니다. 이에 대해 어떻게 생각하시는지 의견 주시면 감사하겠습니다.
> feat: #177 리뷰 대기시간,서빙시간 조회

- src/main/java/com/moyorak/api/image/ImageStore.java
- src/main/java/com/moyorak/api/image/service/ImageService.java
- src/test/java/com/moyorak/api/image/service/ImageStoreTest.java
- 이미지 서비스 재사용을 위해 컴포넌트로 분리
---
- presignurl로 변경하는 기능을 다른 도메인에서 사용하기 위해 이미지 서비스를 컴포넌트로 분리합니다.
> refactor: #217 이미지 서비스 재사용을 위해 컴포넌트로 분리

- src/main/java/com/moyorak/api/party/controller/PartyController.java
- src/main/java/com/moyorak/api/party/domain/Party.java
- src/main/java/com/moyorak/api/party/domain/SelectionVoteInfo.java
- src/main/java/com/moyorak/api/party/dto/PartyAttendeeWithUserProfile.java
- src/main/java/com/moyorak/api/party/dto/PartyGeneralInfoProjection.java
- src/main/java/com/moyorak/api/party/dto/PartyListRequest.java
- src/main/java/com/moyorak/api/party/dto/PartyListResponse.java
- src/main/java/com/moyorak/api/party/dto/PartyListStore.java
- src/main/java/com/moyorak/api/party/dto/PartyRestaurantProjection.java
- src/main/java/com/moyorak/api/party/dto/PartyRestaurantResponse.java
- src/main/java/com/moyorak/api/party/repository/PartyAttendeeRepository.java
- src/main/java/com/moyorak/api/party/repository/PartyRepository.java
- src/main/java/com/moyorak/api/party/repository/PartyRestaurantRepository.java
- src/main/java/com/moyorak/api/party/service/PartyAttendeeService.java
- src/main/java/com/moyorak/api/party/service/PartyFacade.java
- src/main/java/com/moyorak/api/party/service/PartyRestaurantService.java
- src/main/java/com/moyorak/api/party/service/PartyService.java
- src/main/java/com/moyorak/api/party/service/PartyVoteService.java
- src/test/java/com/moyorak/api/party/domain/PartyAttendeeFixture.java
- src/test/java/com/moyorak/api/party/domain/PartyAttendeeWithUserFixture.java
- src/test/java/com/moyorak/api/party/domain/PartyGeneralInfoProjectionFixture.java
- src/test/java/com/moyorak/api/party/domain/PartyRestaurantProjectionFixture.java
- src/test/java/com/moyorak/api/party/dto/PartyListRequestFixture.java
- src/test/java/com/moyorak/api/party/service/PartyFacadeTest.java
- 파티 목록 조회 기능 개발
---
- 파티 목록 조회 기능을 개발 했습니다.
- 투표 타입이 랜덤일 때와, 선택일 때에 따라 화면에서 나와야되는 멘트가 달라야하기 때문에 타입 값을 내립니다.
- 투표 시작 시간을 내려, 투표 까지 시간은 프론트에서 구할 수 있게 했습니다.
- 본인 참가 여부를 확인하기 위해 `Boolean` 값인 `isParticipating` 를 내립니다.
- 파티에 `teamId` ,  일반 투표 정보에 `startDate` 를 추가했습니다.
> feat:#238 파티 목록 조회

- src/main/java/com/moyorak/api/auth/controller/UserController.java
- src/main/java/com/moyorak/api/auth/domain/Gender.java
- src/main/java/com/moyorak/api/auth/domain/User.java
- src/main/java/com/moyorak/api/auth/domain/UserToken.java
- src/main/java/com/moyorak/api/auth/repository/MealTagRepository.java
- src/main/java/com/moyorak/api/auth/repository/UserRepository.java
- src/main/java/com/moyorak/api/auth/service/AuthService.java
- src/main/java/com/moyorak/api/auth/service/MealTagService.java
- src/main/java/com/moyorak/api/auth/service/UserFacade.java
- src/main/java/com/moyorak/api/auth/service/UserService.java
- src/main/java/com/moyorak/api/team/domain/TeamUser.java
- src/main/java/com/moyorak/api/team/repository/TeamUserRepository.java
- src/main/java/com/moyorak/api/team/service/TeamUserService.java
- src/test/java/com/moyorak/api/auth/domain/GenderTest.java
- src/test/java/com/moyorak/api/auth/domain/UserTokenTest.java
- 회원 탈퇴 기능을 추가하였습니다.
회원 탈퇴 기능은 아래와 같은 검증을 통해 처리 되게 됩니다.
1. 팀에 관리자로 속해있는지를 검증합니다.
- 관리자로 되어 있을 경우 탈퇴 reject이 됩니다.
2. 회원 정보를 제거합니다.
- 회원 정보가 존재하지 않는 경우 reject이 됩니다.
3. 과거 팀 소속 정보 제거
4. 비선호 + 알러지 정보 초기화
5. 토큰 초기화
- 로그인 정보가 유효하지 않으면 reject이 됩니다.
- 기능이 많아지면서, 코드를 빠르게 파악하기 어려워 javadoc 주석을 추가하였습니다.
- API 마다의 어떠한 응답을 내려줘야 하는지를 `@ApiResponse`를 통해 직접 명시하였습니다.
- 머지 되면, 테이블의 속성도 수정이 필요합니다. 
- MEMBER
- gender : varchar(6) -> varchar(10)
- profile_image : nullable 
- TEAMUSER
- member_id : nullable
---
- 회원 탈퇴 기능 추가
> feat: #127 회원 탈퇴 기능 추가

- src/main/java/com/moyorak/api/party/domain/RandomVoteInfo.java
- src/main/java/com/moyorak/api/party/domain/SelectionVoteInfo.java
- src/main/java/com/moyorak/api/party/dto/PartySaveRequest.java
- src/main/java/com/moyorak/api/party/service/PartyFacade.java
- src/main/java/com/moyorak/api/party/service/VoteService.java
- 파티 생성하고 목록 조회가 되지 않는다고 하여, 저장할 때 투표 상세 정보도 함께 저장할 수 있도록 추가 하였습니다.
---
- 파티 생성시, 투표 상세 정보도 함께 저장도록 기능 추가
> refactor: #272 파티 생성시, 투표 상세 정보도 함께 저장도록 기능 추가

- src/main/java/com/moyorak/api/party/controller/PartyController.java
- src/main/java/com/moyorak/api/party/domain/Party.java
- src/main/java/com/moyorak/api/party/dto/PartyInfo.java
- src/main/java/com/moyorak/api/party/dto/PartyResponse.java
- src/main/java/com/moyorak/api/party/service/PartyFacade.java
- src/main/java/com/moyorak/api/party/service/PartyService.java
- 응답 dto에 해당 파티가 참석 가능한 파티인지 확인하는 필드 추가
- 팀에 해당하는 파티인지 검증하는 로직 추가
---
dto에 참석 가능한 파티인지 확인하는 필드를 추가하고,
해당 파티가 팀에 속하는지 검증 로직을 추가합니다.
> refactor: #279 파티 상세 조회 시 응답 dto 필드에 참여 가능 여부 필드 추가

- src/main/java/com/moyorak/api/review/service/ReviewFacade.java
- src/main/java/com/moyorak/api/team/repository/TeamRestaurantRepository.java
- 리뷰 수정 시, 빠진 이미지 제거, 새로운 이미지 추가
- 팀 맛집 정보 리뷰 값 업데이트 후, 리뷰 업데이트
- 팀 맛집 정보 업데이트 쿼리 변경
---
- 쿼리에서, `reviewCount` 값이 증감되어 사용되어, 해당 사항 변경
- 리뷰 값이 업데이트 된 상태에서 팀 맛집 값을 변경해, 변경사항이 반영되지 않아 수정
- 이미지 업데이트 로직 변경
> fix:#284 팀 맛집 리뷰 업데이트 쿼리 수정,리뷰 업데이트 시 이미지 수정 로직 변경

- src/main/java/com/moyorak/api/review/service/ReviewFacade.java
- src/main/java/com/moyorak/api/review/service/ReviewPhotoService.java
- src/main/java/com/moyorak/api/review/service/ReviewService.java
- src/main/java/com/moyorak/api/team/repository/TeamRestaurantRepository.java
- src/test/java/com/moyorak/api/review/service/ReviewFacadeTest.java
- 리뷰, 리뷰사진 조회 트랜잭션 변경
- 팀 맛집 정보 음수 되지 못하게 변경
---
- `readonly=True`로 저장이 되지 않아, 변경
- 팀 맛집 정보가 0 보다 작아지지 못하게 조건 문 설정
> fix:#284 리뷰, 리뷰사진 조회 트랜잭션 변경, 팀 맛집 정보 음수 되지 못하게 변경

- src/main/java/com/moyorak/api/review/service/ReviewFacade.java
- src/main/java/com/moyorak/api/team/repository/TeamRestaurantRepository.java
- 벌크 업데이트 전 flush되게 변경
---
- 벌크 업데이트 이전에 있던 영속성 캐시 다 날려 저장이 안돼서 설정 변경
> fix:#284 벌크 업데이트 전 flush되게 변경

- src/main/java/com/moyorak/api/party/service/PartyAttendeeService.java
- 팀 ID 와 파티의 팀 ID 비교 로직 변경
---
파티와 사용자가 같은 팀에 속해 있는지 검증합니다.
> fix: #310 팀 ID 비교 검증 로직 변경

- src/main/java/com/moyorak/api/auth/domain/User.java
- 회원 프로필 이미지 uri 긴게 들어오면 저장이 안되어 512로 자릿수 변경
---
- 회원 프로필 이미지 varchar(256) 에서 varchar(512)로 변경
> chore: #325 회원 프로필 이미지 varchar(256) 에서 varchar(512)로 변경
