DDD-Community/DDD-12-MOYORAK-API

.github/workflows/code-review.yml

- 코드리뷰를 위한 워크플로우를 추가하였습니다. (#3)
---
- CI 워크플로우 추가

ci: 코드리뷰 관련 워크플로우 추가

---

src/main/java/com/ddd/api/config/exception/BusinessException.java
src/main/java/com/ddd/api/config/exception/InvalidResponse.java
src/main/java/com/ddd/api/config/exception/RootExceptionHandler.java
src/main/java/com/ddd/api/config/web/CustomErrorAttributes.java
src/main/java/com/ddd/api/config/web/ErrorAttributesConfig.java
src/main/resources/application.yml

- 프로젝트의 기본이 되는 ControllerAdvice를 추가 하였습니다. (#8)
- 추가로 기본 스프링 MVC 에러 형식을 ProblemDetails 형식으로 변경하였습니다.
---
- ControllerAdvice 추가
- 프로젝트 기본 BusinessException 추가
- 스프링 MVC 에러 형식을 ProblemDetails 형식으로 변경

기본 Exception Handler 추가

---

src/main/java/com/ddd/api/infra/orm/AuditInformation.java
src/main/java/com/ddd/api/infra/orm/JpaConfig.java

- 데이터의 생성과 변경 시간을 관리하기 위한 JPA Auditing 기능을 추가 하였습니다. (#10)
---
- JPA Auditing 추가

feat: JPA Auditing 추가

---

src/main/java/com/moyorak/api/config/exception/domain/DataNotFoundException.java
src/main/java/com/moyorak/api/global/domain/ListRequest.java
src/main/java/com/moyorak/api/global/domain/ListResponse.java
src/main/java/com/moyorak/api/infra/orm/BooleanYnConverter.java
src/main/java/com/moyorak/api/sample/controller/SampleController.java
src/main/java/com/moyorak/api/sample/domain/Sample.java
src/main/java/com/moyorak/api/sample/dto/SampleResponse.java
src/main/java/com/moyorak/api/sample/dto/SampleSaveRequest.java
src/main/java/com/moyorak/api/sample/dto/SampleSearchRequest.java
src/main/java/com/moyorak/api/sample/dto/SampleUpdateRequest.java
src/main/java/com/moyorak/api/sample/repository/SampleRepository.java
src/main/java/com/moyorak/api/sample/service/SampleService.java
src/test/java/com/moyorak/api/helper/ConverterHelper.java
src/test/java/com/moyorak/api/helper/TestFixtureUtils.java
src/test/java/com/moyorak/api/sample/controller/SampleControllerTest.java
src/test/java/com/moyorak/api/sample/domain/SampleFixture.java
src/test/java/com/moyorak/api/sample/domain/SampleTest.java
src/test/java/com/moyorak/api/sample/dto/SampleSaveRequestFixture.java
src/test/java/com/moyorak/api/sample/dto/SampleSearchRequestFixture.java
src/test/java/com/moyorak/api/sample/dto/SampleUpdateRequestFixture.java
src/test/java/com/moyorak/api/sample/service/SampleServiceTest.java

- 간단한 샘플용 API 추가 (#18)
---
- Sample API 추가 및 테스트 코드 작성

sample api 추가

---

src/main/java/com/moyorak/MoyorakApplication.java
src/main/java/com/moyorak/api/sample/controller/SampleController.java
src/main/java/com/moyorak/api/sample/domain/Sample.java
src/main/java/com/moyorak/api/sample/dto/SampleSearchRequest.java
src/main/java/com/moyorak/api/sample/service/SampleService.java
src/main/java/com/moyorak/config/exception/BusinessException.java
src/main/java/com/moyorak/config/exception/InvalidResponse.java
src/main/java/com/moyorak/config/exception/RootExceptionHandler.java
src/main/java/com/moyorak/config/exception/domain/DataNotFoundException.java
src/main/java/com/moyorak/config/web/CustomErrorAttributes.java
src/main/java/com/moyorak/config/web/ErrorAttributesConfig.java
src/main/java/com/moyorak/global/domain/ListRequest.java
src/main/java/com/moyorak/global/domain/ListResponse.java
src/main/java/com/moyorak/infra/orm/AuditInformation.java
src/main/java/com/moyorak/infra/orm/BooleanYnConverter.java
src/main/java/com/moyorak/infra/orm/JpaConfig.java
src/main/java/com/moyorak/infra/swagger/SwaggerConfig.java
src/test/java/com/moyorak/api/helper/ConverterHelper.java
src/test/java/com/moyorak/api/sample/controller/SampleControllerTest.java
src/test/java/com/moyorak/api/sample/service/SampleServiceTest.java

패키지 변경을 하였습니다. (#23)
비즈니스 관련 패키지가 많아질수록 패키지 관리가 어려울 것을 대비하여
비즈니스 관련의 경우 `api`하위로 분리할 수 있도록 하였습니다.
해당 PR이 머지가 된다면, 바로 적용하셔야만 충돌 발생하지 않습니다!
---
- 패키지 구조 변경

chore: #23 패키지 구조 변경

---

.github/workflows/ecr-deploy.yml

- ECR 저장소에 이미지 저장할 때, AWS 인증 정보 가져올 수 있도록 추가
---
- 불필요한 step 제거
- aws-actions/configure-aws-credentials@v2 추가

build: #31 AWS 인증 처리할 수 있도록 과정 추가

---

.github/workflows/deploy.yml

- SSH KEY를 디코딩 하는 불필요한 step을 제거합니다.
---
- 불필요한 step 제거

build: #34 불필요한 step 삭제

---

.github/workflows/deploy.yml

- Github Action의 IP를 인바우늗 규칙에 동적으로 추가할 수 있도록 step을 추가 하였습니다.
---
- step을 추가

build: #34 Github Action IP 인바운드에 동적으로 추가할 수 있도록 step 추가

---

.github/workflows/add-inbound.yml

- IP 변수 누락으로 인하여 추가
---
- IP 포트 인바운드 규칙 등록 파이프라인에 변수 선언

chore: #65 IP 변수 선언

---

.github/workflows/add-inbound.yml

- 인바운드 규칙 추가 후, IP가 로그에 남아 이를 제거하기 위한 설정 추가
---
- 인바운드 규칙 추가 후, IP가 로그에 남아 이를 제거하기 위한 설정 추가

chore: #65 인바운드 규칙 추가 후 로그 보이지 않도록 설정 추가

---

.github/workflows/add-inbound.yml

- IP를 직접 입력하는 것이 아닌, 동적으로 받을 수 있도록 변경
---
- IP 입력 방식 변경

chore: #65 IP 정보는 동적으로 받을 수 있도록 변경

---

.github/workflows/add-inbound.yml

- IP가 계속 로그에 노출되기에 이를 방지하고자 환경별 시크릿을 사용하기로 변경
---
- 사용자 선택시 해당 환경으로 실행될 수 있도록 볌경

refactor: #72 아이피를 환경별 시크릿을 통해 가지고올 수 있도록 변경

---

.github/workflows/add-inbound.yml

- 포트 선언을 빼먹어서 추가 했습니다 ㅜㅜ 제발 되거라
---
- PORT 변수 선언

fix: #72 PORT 변수 선언

---

.github/workflows/add-inbound.yml

- 명령어 이어주기 위한  \ 추가...
---
-  \ 추가

fix: #72 \ 추가

---

.github/workflows/deploy.yml

- 배포 완료 후, 디스코드 웹훅으로 메세지 전송할 수 있도록 파이프라인을 수정하였습니다.
---
- `deploy.yml` 배포 여부에 따른 메세지 전송 스텝 추가

feat: #63 배포 완료 여부 디스코드 웹훅으로 메세지 전송

---

src/main/java/com/moyorak/api/auth/controller/UserController.java
src/main/java/com/moyorak/api/auth/domain/Gender.java
src/main/java/com/moyorak/api/auth/domain/User.java
src/main/java/com/moyorak/api/auth/dto/SignUpRequest.java
src/main/java/com/moyorak/api/auth/dto/SignUpResponse.java
src/main/java/com/moyorak/api/auth/repository/UserRepository.java
src/main/java/com/moyorak/api/auth/service/UserService.java
src/main/java/com/moyorak/config/security/CustomOAuth2SuccessHandler.java
src/main/java/com/moyorak/config/security/CustomOAuth2UserService.java
src/main/java/com/moyorak/config/security/JwtAuthenticationFilter.java
src/main/java/com/moyorak/config/security/SecurityConfig.java
src/main/java/com/moyorak/infra/orm/SecurityAuditorAware.java
src/test/java/com/moyorak/api/auth/domain/GenderTest.java
src/test/java/com/moyorak/api/auth/dto/SignUpRequestFixture.java
src/test/java/com/moyorak/api/auth/service/UserServiceTest.java

- 회원 가입 관련 API를 추가하였습니다.
---
- 최초 회원 가입 할 때, `Google Oauth2`로 접근하고 나서 모여락으로 돌아올 때, 이메일, 회원 이름, 회원 이미지 URL을 반환해줄 수 있도록 변경하였습니다.
- 회원 가입 관련 기능 추가
- 테스트 코드 추가

feat: #85 회원 가입 기능을 개발합니다

---

src/main/java/com/moyorak/api/restaurant/domain/Restaurant.java
src/main/java/com/moyorak/api/restaurant/dto/RestaurantSaveRequest.java
src/test/java/com/moyorak/api/restaurant/controller/RestaurantControllerTest.java
src/test/java/com/moyorak/api/restaurant/domain/RestaurantFixture.java
src/test/java/com/moyorak/api/restaurant/domain/RestaurantTest.java
src/test/java/com/moyorak/api/restaurant/service/RestaurantServiceTest.java

- 식당 엔티티에 도로명 추가
- 식당 저장 리퀘스트 디티오에 도로명 추가
- 테스트 코드 수정
---
도로명을 저장하기 위해 엔티티와 디티오를 수정했습니다.

feat: #104 도로명 지번 주소 모두 저장되도록 수정

---

src/main/java/com/moyorak/api/team/domain/Team.java
src/main/java/com/moyorak/api/team/domain/TeamPlace.java

- 팀 엔티티 생성
- 팀 식당 엔티티 생성
---
- 간단하게 팀과 팀 식당 엔티티를 생성했습니다. 일단 러프하게 작성한 거라 api 개발하면서 다듬겠습니다~!

feat: #117 팀, 팀식당 엔티티 생성

---

src/main/java/com/moyorak/api/review/Review.java
src/main/java/com/moyorak/api/review/ReviewPhoto.java

- 리뷰 엔티티 생성
- 리뷰 사진 엔티티 생성
---
- 식당 상세 조회 개발을 위해 리뷰와 리뷰 사진 엔티티 생성을 했습니다. API 생성을 하면서 보완해나갈 예정입니다.

feat: #120 리뷰 테이블 생성

---

src/main/java/com/moyorak/api/team/controller/TeamRestaurantController.java
src/main/java/com/moyorak/api/team/dto/TeamRestaurantLocation.java
src/main/java/com/moyorak/api/team/dto/TeamRestaurantLocationsResponse.java
src/main/java/com/moyorak/api/team/repository/TeamRestaurantRepository.java
src/main/java/com/moyorak/api/team/service/TeamRestaurantService.java

- 팀의 모든 맛집 위치를 조회합니다.
---
- 팀 맛집 위치 조회 api 개발

feat: #137 팀 맛집 모든 위치 조회

---

src/main/java/com/moyorak/api/review/dto/PhotoPath.java
src/main/java/com/moyorak/api/review/repository/ReviewPhotoRepository.java
src/main/java/com/moyorak/api/review/service/ReviewPhotoService.java
src/main/java/com/moyorak/api/team/controller/TeamRestaurantController.java
src/main/java/com/moyorak/api/team/dto/TeamRestaurantReviewPhotoRequest.java
src/main/java/com/moyorak/api/team/service/TeamRestaurantReviewFacade.java
src/test/java/com/moyorak/api/review/service/ReviewPhotoServiceTest.java
src/test/java/com/moyorak/api/team/dto/TeamRestaurantReviewPhotoRequestFixture.java
src/test/java/com/moyorak/api/team/service/TeamRestaurantReviewFacadeTest.java

- 팀 맛집 리뷰 사진 조회 기능 개발
---
- 팀 맛집 리뷰 사진 조회 테스트 및 파사드 테스트 공통 객체 생성
- 팀 맛집 리뷰 및 리뷰 사진 조회 메서드명 구체화

팀 맛집 리뷰 사진 조회

---

src/main/java/com/moyorak/api/company/controller/CompanyController.java
src/main/java/com/moyorak/api/company/domain/Company.java
src/main/java/com/moyorak/api/company/domain/CompanySearch.java
src/main/java/com/moyorak/api/company/dto/CompanySaveRequest.java
src/main/java/com/moyorak/api/company/dto/CompanySearchListResponse.java
src/main/java/com/moyorak/api/company/dto/CompanySearchRequest.java
src/main/java/com/moyorak/api/company/dto/CompanySearchResponse.java
src/main/java/com/moyorak/api/company/repository/CompanyRepository.java
src/main/java/com/moyorak/api/company/repository/CompanySearchRepository.java
src/main/java/com/moyorak/api/company/service/CompanyService.java
src/test/java/com/moyorak/api/company/domain/CompanyFixture.java
src/test/java/com/moyorak/api/company/domain/CompanySearchFixture.java
src/test/java/com/moyorak/api/company/dto/CompanySearchRequestTest.java
src/test/java/com/moyorak/api/company/service/CompanyServiceTest.java
src/test/java/com/moyorak/api/team/service/TeamRestaurantServiceTest.java

- 회사 저장 기능 개발
- 회사 검색 기능 개발
---
- 회사 저장 시, 회사 검색 테이블에 동시 저장
- 회사 검색 기능 개발
- 기존 코드와 동일한 내용이 많아서, 두가지 기능을 한번에 만들어서 올리게 됐습니다.

feature/158 회사 저장, 검색 기능 개발

---

src/main/java/com/moyorak/api/history/controller/SearchHistoryController.java
src/main/java/com/moyorak/api/history/dto/SearchHistoryListResponse.java
src/main/java/com/moyorak/api/history/dto/SearchHistoryRequest.java
src/main/java/com/moyorak/api/history/dto/SearchHistoryResponse.java
src/main/java/com/moyorak/api/history/repository/SearchHistoryRepository.java
src/main/java/com/moyorak/api/history/service/SearchHistoryService.java
src/test/java/com/moyorak/api/history/domain/SearchHistoryFixture.java
src/test/java/com/moyorak/api/history/service/SearchHistoryServiceTest.java

- 본인의 팀 맛집 검색 기록 조회 기능 개발
---
본인의 팀 맛집 검색 기록 조회 기능을 개발했습니다.

feat: #154 본인 검색 기록 조회

---

src/main/java/com/moyorak/api/history/controller/SearchHistoryController.java
src/main/java/com/moyorak/api/history/domain/SearchHistory.java
src/main/java/com/moyorak/api/history/repository/SearchHistoryRepository.java
src/main/java/com/moyorak/api/history/service/SearchHistoryService.java
src/test/java/com/moyorak/api/history/domain/SearchHistoryFixture.java
src/test/java/com/moyorak/api/history/domain/SearchHistoryTest.java
src/test/java/com/moyorak/api/history/service/SearchHistoryServiceTest.java

- 본인 검색 기록 삭제 기능 개발
---
본인 검색 기록 삭제 기능을 개발했습니다. 
기존 리스트 쿼리 설명문을 수정했습니다.

feat: #161 본인 팀 맛집 검색 기록 삭제

---

src/main/java/com/moyorak/api/history/controller/ViewHistoryController.java
src/main/java/com/moyorak/api/history/domain/ViewHistory.java
src/main/java/com/moyorak/api/history/repository/ViewHistoryRepository.java
src/main/java/com/moyorak/api/history/service/ViewHistoryService.java
src/test/java/com/moyorak/api/history/domain/ViewHistoryFixture.java
src/test/java/com/moyorak/api/history/domain/ViewHistoryTest.java
src/test/java/com/moyorak/api/history/service/ViewHistoryServiceTest.java

- 본인 팀 맛집 상세 조회 기록 삭제 기능 개발
---
팀 맛집 조회 기록 삭제 기능을 개발했습니다.

feat: #162 본인 팀 맛집 상세 조회 기록 삭제

---

src/main/java/com/moyorak/config/web/WebConfig.java

- CORS 설정 추가하였습니다. 임시적으로 모든 설정을 열어 두었습니다.
---
- CORS 설정 추가

chore: #179 CORS 설정 추가

---

.github/workflows/deploy.yml
.github/workflows/gradle.yml
src/main/resources/application-dev.yml

- 잘못된 환경변수가 있어서 수정하였습니다.
---
- 잘못된 환경변수 수정

chore: #157 환경변수 및 배포 스크립트 수정

---

.github/workflows/deploy.yml

- 환경 변수로 등록해 놓은 값을 가져오기 위해서 수정하였습니다.
`secrets -> env`
사실 되는지는 잘 모르겠어요 ㅠㅠ
---
- 환경 변수 호출 방법 수정

chore: #157 환경 변수 관련 수정

---

.github/workflows/deploy.yml

- env가 안되어서 vars로 키워드 수정 해 보았습니다.
---
- 환경 변수 호출 방법 env -> vars로 수정

chore: #157 환경 변수 호출 방법 env -> vars로 수정

---

src/main/java/com/moyorak/api/team/controller/TeamUserController.java
src/main/java/com/moyorak/api/team/domain/TeamUser.java
src/main/java/com/moyorak/api/team/repository/TeamRepository.java
src/main/java/com/moyorak/api/team/repository/TeamSearchRepository.java
src/main/java/com/moyorak/api/team/repository/TeamUserRepository.java
src/main/java/com/moyorak/api/team/service/TeamJoinFacade.java
src/main/java/com/moyorak/api/team/service/TeamService.java
src/main/java/com/moyorak/api/team/service/TeamUserService.java
src/test/java/com/moyorak/api/team/service/TeamUserServiceTest.java

- 팀 가입 신청  기능 개발
- 팀 가입 신청 승인 기능 개발
---
- 하나의 기능 묶음 이기도 하고, 같은 클래스들을 건드리기 때문에 한번에 개발 하게 됐습니다.
- 거절의 경우, 탈퇴와 비슷 한것 같기도 하고, 거절 후, 프로세스에 대해 정의가 되있는 것 같지가 않아. 추가 하지 않았습니다.
- 거절 기능은 질문에 대한 답변을 들은 후 개발 하겠습니다.
- 팀 레퍼지토리 이름이 겹쳐, 팀 조회 레퍼지토리 이름을 `TeamSearchRepository` 로 변경 했습니다.

feat: #167 팀 가입 신청,승인 기능 개발

---

src/main/resources/application-dev.yml

-  access token 만료 시간 하루로 변경
---
- 개발환경에서 access token 만료 시간 하루로 변경합니다.

chore: #185 개발환경에서 access token 만료 시간 하루로 변경

---

src/main/java/com/moyorak/api/auth/controller/UserController.java
src/main/java/com/moyorak/api/auth/dto/OAuthResponse.java
src/main/java/com/moyorak/api/auth/dto/SignUpResponse.java
src/main/java/com/moyorak/api/auth/service/UserService.java
src/main/java/com/moyorak/config/security/CustomOAuth2SuccessHandler.java
src/main/java/com/moyorak/infra/orm/SecurityAuditorAware.java

- 회원 가입 후, 로그인을 위해 회원 고유 ID를 반환하도록 수정
---
- 회원 가입시 회원 고유 ID 반환

refactor: #199 회원 가입 후 응답으로 회원 id를 반환한다

---

src/main/java/com/moyorak/api/image/service/ImageService.java
src/main/java/com/moyorak/api/review/service/ReviewPhotoService.java
src/main/java/com/moyorak/api/team/service/TeamRestaurantReviewFacade.java
src/test/java/com/moyorak/api/review/service/ReviewPhotoServiceTest.java
src/test/java/com/moyorak/api/team/service/TeamRestaurantReviewFacadeTest.java

- 리뷰 조회 시, 이미지 path 변경
---
- 리뷰 조회 시, 이미지 path 변경 되게 이미지 서비스에서 presignedUrl 로변경

refactor: #205 리뷰 조회 시, 이미지 path 변경

---

src/main/java/com/moyorak/config/security/CustomOAuth2SuccessHandler.java
src/main/java/com/moyorak/config/security/SecurityProperties.java
src/main/resources/application-dev.yml
src/main/resources/application.yml

- dev 환경에서는 클라이언트로, local에서는 local로 리다이렉트 하도록 수정하였습니다.
---
- OAuth 성공 시, 클라이언트로 리다이렉트 하도록 수정

refactor: #207 OAuth 성공 시 클라이언트로 리다이렉트 하도록 수정

---

src/main/resources/application-dev.yml

- 클라이언트 https 관련 설정 추가
---
- 클라이언트 https 관련 설정 추가

chore: #214 클라이언트 https 관련 설정 추가

---

src/main/java/com/moyorak/api/image/ImageStore.java
src/main/java/com/moyorak/api/image/service/ImageService.java
src/main/java/com/moyorak/api/review/domain/ReviewPhotoPaths.java
src/main/java/com/moyorak/api/review/dto/PhotoPath.java
src/main/java/com/moyorak/api/review/service/ReviewPhotoService.java
src/main/java/com/moyorak/api/team/service/TeamRestaurantReviewFacade.java
src/test/java/com/moyorak/api/team/service/TeamRestaurantReviewFacadeTest.java

-팀 맛집 리뷰 이미지 경로 변환 코드 수정
---
- 이미지스토어 주입
- 이미지 경로 변환 코드 수정

refactor: #220 팀 맛집 리뷰 이미지 경로 변환 코드 수정

---

src/main/java/com/moyorak/api/auth/dto/SignUpRequest.java
src/main/java/com/moyorak/api/company/controller/CompanyController.java
src/main/java/com/moyorak/api/team/controller/TeamController.java
src/main/java/com/moyorak/config/security/JwtAuthenticationFilter.java

- 기존에 토큰 필요 없이 처리가능하도록 수정 했던 API들 다시 토큰이 필요하도록 설정 변경 하였습니다.
- 불필요한 주석 제거하였습니다.
- [회원가입 플로우](https://github.com/DDD-Community/DDD-12-MOYORAK-API/wiki/%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85-%ED%94%8C%EB%A1%9C%EC%9A%B0) 를 통해서  회원가입 플로우를 정리하였습니다.
---
- 불필요한 주석 제거
- 토큰 요구하도록 수정

refactor: #135 온보딩 과정을 Step별로 나눠 처리한다.

---

src/main/java/com/moyorak/api/party/domain/Party.java
src/main/java/com/moyorak/api/party/domain/PartyAttendee.java

- 파티 테이블 생성
-  파티 참가자 테이블 생성
---
- 작업을 위해 기초적인 내용만 채웠으니, 추후 작업 하면서 채워가면 될것 같습니다.

feat:#232 팟, 팟 참가자 테이블 생성

---

src/main/java/com/moyorak/api/company/controller/CompanyController.java
src/main/java/com/moyorak/api/company/dto/CompanyPositionResponse.java
src/main/java/com/moyorak/api/company/repository/CompanyRepository.java
src/main/java/com/moyorak/api/company/service/CompanyService.java
src/test/java/com/moyorak/api/company/service/CompanyServiceTest.java

- 회사의 위도 및 경도 조회
---
해당 api 호출하기전에 프론트에서 회사 ID를 저장하고 있다고 하여 회사 ID로 바로 조회하도록 개발했습니다.

feat: #233 회사의 위도, 경도를 조회한다.

---

src/main/java/com/moyorak/api/party/controller/PartyAttendeeController.java
src/main/java/com/moyorak/api/party/domain/PartyAttendee.java
src/main/java/com/moyorak/api/party/dto/PartyAttendRequest.java
src/main/java/com/moyorak/api/party/repository/PartyAttendeeRepository.java
src/main/java/com/moyorak/api/party/repository/PartyRepository.java
src/main/java/com/moyorak/api/party/service/PartyAttendeeService.java
src/test/java/com/moyorak/api/party/domain/PartyFixture.java
src/test/java/com/moyorak/api/party/service/PartyAttendeeServiceTest.java

- 파티 참여하기 기능 개발
---
파티 참여하기 기능을 개발했습니다.
파티가 속한 팀에 요청자가 가입하지 않은 상황이면 참여하기가 불가능하도록 구현했습니다.

feat: #243 파티 참여하기

---

src/main/java/com/moyorak/api/party/service/PartyFacade.java
src/main/java/com/moyorak/api/party/service/VoteService.java
src/test/java/com/moyorak/api/party/service/PartyFacadeTest.java

- 파티 목록 조회 시, 상태 값 변경
---
- 파티 목록 조회 시, 상태 값 변경

refactor: #247 파티 목록 조회 시, 상태 값 변경

---

src/main/java/com/moyorak/api/party/controller/PartyController.java

- 팟 목록 조회 리퀘스트 파싱 이슈 해결
---
- 팟 목록 조회 리퀘스트 바디 어노테이션 제거

fix: #252 팟 목록 조회 리퀘스트 파싱 이슈 해결

---

src/main/java/com/moyorak/api/party/controller/PartyController.java
src/main/java/com/moyorak/api/party/domain/Party.java
src/main/java/com/moyorak/api/party/domain/PartyAttendee.java
src/main/java/com/moyorak/api/party/domain/Vote.java
src/main/java/com/moyorak/api/party/domain/VoteRestaurantCandidate.java
src/main/java/com/moyorak/api/party/domain/VoteType.java
src/main/java/com/moyorak/api/party/dto/PartySaveRequest.java
src/main/java/com/moyorak/api/party/dto/PartySaveRestaurantRequest.java
src/main/java/com/moyorak/api/party/dto/PartySaveRestaurantSelectionRequest.java
src/main/java/com/moyorak/api/party/dto/PartySaveRestaurantsRequest.java
src/main/java/com/moyorak/api/party/dto/PartySaveUserRequest.java
src/main/java/com/moyorak/api/party/dto/PartySaveUserSelectionRequest.java
src/main/java/com/moyorak/api/party/dto/PartySaveUsersRequest.java
src/main/java/com/moyorak/api/party/dto/PartySaveVoteRequest.java
src/main/java/com/moyorak/api/party/service/PartyAttendeeService.java
src/main/java/com/moyorak/api/party/service/PartyFacade.java
src/main/java/com/moyorak/api/party/service/PartyRestaurantService.java
src/main/java/com/moyorak/api/party/service/PartyService.java
src/main/java/com/moyorak/api/party/service/VoteService.java
src/main/java/com/moyorak/api/team/service/TeamService.java
src/test/java/com/moyorak/api/party/domain/VoteTypeTest.java
src/test/java/com/moyorak/api/party/dto/PartySaveVoteRequestFixture.java
src/test/java/com/moyorak/api/party/dto/PartySaveVoteRequestTest.java

- 파티 생성 기능을 추가하였습니다.
- 투표 시간할 때, 투표 시작 시간과 투표 종료 시간 같은 유효성 검증 로직을 상세하게 작성하였습니다.
---
- 파티 생성 기능을 추가

feat: #244 파티 및 투표 생성 기능 추가

---

src/main/java/com/moyorak/api/party/dto/PartyGeneralInfoProjection.java
src/main/java/com/moyorak/api/party/dto/PartyListResponse.java
src/main/java/com/moyorak/api/party/repository/PartyRepository.java
src/test/java/com/moyorak/api/party/domain/PartyGeneralInfoProjectionFixture.java
src/test/java/com/moyorak/api/party/service/PartyFacadeTest.java

- 파티 목록 조회 시, 투표 종료 시간 추가
---
- 파티 목록 조회 시, 투표 종료 시간 추가

refactor:#261 파티 목록 조회 시, 투표 종료 시간 추가

---

src/main/java/com/moyorak/api/company/controller/CompanyController.java
src/main/java/com/moyorak/api/company/dto/CompanySaveResponse.java
src/main/java/com/moyorak/api/company/service/CompanyService.java

- 회사 저장 시, 등록한 회사에 대한 ID 값을 반환하도록 수정하였습니다.
---
- 회사 저장 시, 등록 회사 ID 반환

refactor: #276 회사 저장 시, 등록한 회사에 대한 ID 값을 반환하도록 수정

---

src/main/java/com/moyorak/api/party/controller/PartyController.java
src/main/java/com/moyorak/api/party/dto/PartyResponse.java
src/main/java/com/moyorak/api/party/dto/Voter.java
src/main/java/com/moyorak/api/party/dto/VoterResponse.java
src/main/java/com/moyorak/api/party/repository/PartyAttendeeRepository.java
src/main/java/com/moyorak/api/party/repository/VoteRecordRepository.java
src/main/java/com/moyorak/api/party/service/PartyAttendeeService.java
src/main/java/com/moyorak/api/party/service/PartyFacade.java

- 파티 상세 조회 시 응답 dto에 참석 유무 필드 추가

refactor: #269 파티 상세 조회에서 참석 유무 응답 필드 추가

---

src/main/java/com/moyorak/api/party/controller/VoteController.java
src/main/java/com/moyorak/api/party/domain/VoteRecord.java
src/main/java/com/moyorak/api/party/dto/VoteRequest.java
src/main/java/com/moyorak/api/party/repository/PartyRestaurantRepository.java
src/main/java/com/moyorak/api/party/repository/VoteRecordRepository.java
src/main/java/com/moyorak/api/party/service/PartyAttendeeService.java
src/main/java/com/moyorak/api/party/service/PartyRestaurantService.java
src/main/java/com/moyorak/api/party/service/VoteFacade.java
src/main/java/com/moyorak/api/party/service/VoteRecordService.java
src/main/java/com/moyorak/api/party/service/VoteService.java
src/main/java/com/moyorak/api/team/service/TeamUserService.java
src/test/java/com/moyorak/api/party/domain/PartyInfoFixture.java
src/test/java/com/moyorak/api/party/domain/VoteRecordFixture.java
src/test/java/com/moyorak/api/party/dto/VoteRequestFixture.java
src/test/java/com/moyorak/api/party/service/VoteFacadeTest.java

- 투표 기능 개발
---
- 투표 기능 개발
- 각 항목들에 대한 유효성 체크 기능 개발
- 파사드에서 호출하기위해 각 서비스들 에 해당 메소드들 개발

feat:#264 투표 기능 개발

---

src/main/java/com/moyorak/api/team/repository/TeamRestaurantRepository.java
src/main/java/com/moyorak/api/team/service/TeamRestaurantService.java

- 존재하는 팀 맛집만 조회하도록 페이징 처리
---
존재하는 팀 맛집만 조회하도록 페이징 처리하도록 레포지토리에서 쿼리를 변경했습니다.

fix: #305 존재하는 팀 맛집만 조회하도록 페이징 처리

---

src/main/java/com/moyorak/api/team/controller/TeamUserController.java
src/main/java/com/moyorak/api/team/dto/TeamUserListResponse.java
src/main/java/com/moyorak/api/team/service/TeamUserManagementService.java

- 팀원 목록 응답 dto 변경(팀 이름 추가)
---
팀원 목록 응답에 팀 이름을 추가합니다.

refactor: #301 팀원 목록 조회에 팀 이름 추가

---

README.md

- DDD 동아리 최종 발표를 맞이하여 프로젝트 README.md 업데이트하였습니다.
---
- README.md 업데이트

docs: #314 README.md 업데이트

---

src/main/java/com/moyorak/api/auth/dto/ReviewWithUserAndTeamRestaurantProjection.java
src/main/java/com/moyorak/api/auth/dto/UserReviewResponse.java
src/main/java/com/moyorak/api/auth/service/UserReviewFacade.java
src/main/java/com/moyorak/api/review/domain/ReviewTimeLabels.java
src/main/java/com/moyorak/api/review/repository/ReviewRepository.java
src/main/java/com/moyorak/api/review/service/ReviewService.java
src/test/java/com/moyorak/api/auth/dto/ReviewWithUserAndTeamRestaurantProjectionFixture.java
src/test/java/com/moyorak/api/auth/service/UserReviewFacadeTest.java

- 내 리뷰 조회 시, 팀 맛집 정보 추가
---
- 내 리뷰 조회 시, 팀 맛집 정보를 추가 하기 때문에 기존에 공통으로 사용했던 `ReviewWithUserProjection` 에서 `ReviewWithUserAndTeamRestaurantProjection` 생성 후 변경

refactor:#316 내 리뷰 조회 시, 팀 맛집 정보 추가

---

src/main/java/com/moyorak/api/auth/controller/UserController.java
src/main/java/com/moyorak/api/auth/dto/UserOrganisationResponse.java
src/main/java/com/moyorak/api/team/service/TeamUserService.java

- 팀, 회사 ID 조회시 팀 역할 필드 추가
---
- 팀, 회사 ID 조회를 자신의 팀 정보 조회로 변경하며 팀 필드를 추가합니다.

refactor: #318 팀 역할 필드 추가

---

src/main/java/com/moyorak/api/auth/dto/ReviewWithUserAndTeamRestaurantProjection.java
src/main/java/com/moyorak/api/auth/dto/UserReviewResponse.java
src/main/java/com/moyorak/api/review/repository/ReviewRepository.java
src/test/java/com/moyorak/api/auth/dto/ReviewWithUserAndTeamRestaurantProjectionFixture.java

- 내 리뷰 조회 시, 팀 맛집 삭제 여부 추가
---
- `TeamRestaurant` 의 `use` 조회 추가 후, 해당 값 리턴 되게 변경

refactor:#320 내 리뷰 조회 시, 팀 맛집 삭제 여부 추가

---

src/main/java/com/moyorak/api/team/controller/TeamUserController.java
src/main/java/com/moyorak/api/team/service/TeamUserManagementService.java
src/test/java/com/moyorak/api/team/service/TeamUserManagementServiceTest.java

팀 역할 변경을 팀 매니저 양도 기능으로 변경
---
팀 역할 변경을 팀 매니저 양도 기능으로 변경

feat: #322 팀 매니저 양도 기능으로 변경

---

src/main/java/com/moyorak/api/team/repository/TeamRepository.java

- 간결하고 명확하게 변경 내용을 요약해주세요.
- 예시 내용은 모두 제거하고 작성해주세요.
---
- 어떤 작업을 했는지 한두 줄로 설명해주세요.
예)
- Spotless + pre-commit hook 적용
- 코드 포맷 자동화 기능 도입

fix: #329 쿼리 수정
